#!/usr/bin/env python3
"""Expand the shot list into everything you actually paste and track.

    python production/build_prompts.py

Outputs
-------
prompts/SH-###.txt          fully assembled, paste-ready prompt per shot
prompts/_ALL.md             every prompt in one scrollable file
shots/ep01-shotlist.csv     the production tracker
shots/sequences/seq-##.md   human-readable shot cards

Also runs the continuity validator. Any FAIL must be fixed before you generate.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "production"))
sys.path.insert(0, str(ROOT / "shots"))

import blocks as B  # noqa: E402
from ep01_shots import SEQUENCES, SHOTS  # noqa: E402

LENS_HINT = {
    "18mm": "18mm wide angle lens",
    "35mm": "35mm lens",
    "50mm": "50mm lens",
    "85mm": "85mm lens, shallow depth of field",
    "macro": "macro lens, extreme close focus",
}

HEIGHT_HINT = {
    "toy": "camera positioned very low at toy eye height, roughly 40mm off the ground",
    "ground": "camera at ground level looking steeply upward, heavy foreshortening",
    "eye": "camera at the boy's own eye level",
    "high": "camera high above looking down",
    "n/a": "",
}


def assemble(shot: dict) -> str:
    """Build the full paste-ready prompt for one shot."""
    parts: list[str] = []

    parts.append(f"SHOT: {shot['action']}")

    cam = f"CAMERA: {LENS_HINT[shot['lens']]}, {shot['move']}"
    if HEIGHT_HINT.get(shot["height"]):
        cam += f", {HEIGHT_HINT[shot['height']]}"
    parts.append(cam + ".")

    for key in shot["chars"]:
        parts.append(B.CHARACTERS[key])

    if shot["chars"] and any(k != "KIT" for k in shot["chars"]):
        parts.append(B.ON_TWOS)

    if shot.get("kit_state") and "KIT" in shot["chars"]:
        parts.append(B.KIT_STATES[shot["kit_state"]])

    parts.append(B.PLATES[shot["plate"]])

    if shot.get("hand"):
        parts.append(B.HAND[shot["hand"]])

    horizon = B.smooth_phrase(shot.get("smooth", 0))
    if horizon:
        parts.append(horizon)

    if shot.get("extra"):
        parts.append(shot["extra"])

    parts.append(B.STYLE_LOCK)
    parts.append(B.NEGATIVE_LOCK)

    return "\n\n".join(p.strip() for p in parts if p and p.strip())


# ------------------------------------------------------------------ validation

def validate() -> list[str]:
    fails: list[str] = []

    ids = [s["id"] for s in SHOTS]
    if len(ids) != len(set(ids)):
        fails.append("duplicate shot ids")

    total = sum(s["dur"] for s in SHOTS)

    for s in SHOTS:
        sid = s["id"]
        if s["dur"] not in (5, 10):
            fails.append(f"{sid}: duration {s['dur']} — must be 5 or 10 (rule 1)")
        if s["plate"] not in B.PLATES:
            fails.append(f"{sid}: unknown plate {s['plate']}")
        for k in s["chars"]:
            if k not in B.CHARACTERS:
                fails.append(f"{sid}: unknown character block {k}")
        if s.get("hand") and s["hand"] not in B.HAND:
            fails.append(f"{sid}: unknown hand state {s['hand']}")
        if s.get("kit_state") and s["kit_state"] not in B.KIT_STATES:
            fails.append(f"{sid}: unknown kit state {s['kit_state']}")
        if s.get("chain") and s["chain"] not in ids:
            fails.append(f"{sid}: chains from unknown shot {s['chain']}")
        if s["move"].count(",") > 0:
            fails.append(f"{sid}: more than one camera move")

    # rule 8 — the Smooth horizon never retreats once it has appeared, except
    # in interiors and in the Deep Bin, which are marked 0 and skipped.
    seen = 0
    for s in SHOTS:
        v = s.get("smooth", 0)
        if v == 0:
            continue
        if v < seen and s["seq"] < 7:
            fails.append(f"{s['id']}: Smooth horizon retreated {seen} -> {v} (rule 8)")
        seen = max(seen, v)

    # rule 11 — Colossus is never whole before SH-080
    for s in SHOTS:
        if "COLOSSUS_FINISHED" in s["chars"] and s["id"] < "SH-080":
            fails.append(f"{s['id']}: Colossus finished before SH-080")

    print(f"  {len(SHOTS)} shots, {total}s total ({total // 60}:{total % 60:02d})")
    if total != 610:
        fails.append(f"runtime is {total}s, target is 610s")

    return fails


# ------------------------------------------------------------------ writers

def write_prompts() -> None:
    out = ROOT / "prompts"
    out.mkdir(exist_ok=True)
    for f in out.glob("*.txt"):
        f.unlink()

    combined = ["# FIRST LAYER — all shot prompts\n",
                "Generated by `production/build_prompts.py`. Do not edit by hand — "
                "edit `shots/ep01_shots.py` or `production/blocks.py` and re-run.\n"]

    for s in SHOTS:
        body = assemble(s)
        (out / f"{s['id']}.txt").write_text(body + "\n")
        combined.append(
            f"\n---\n\n## {s['id']} · {s['dur']}s · {s['tool']} · seq {s['seq']}\n\n"
            f"```\n{body}\n```\n"
        )

    (out / "_ALL.md").write_text("\n".join(combined))
    print(f"  wrote {len(SHOTS)} prompt files -> prompts/")


CSV_FIELDS = [
    "id", "seq", "dur", "tool", "plate", "chars", "lens", "move", "height",
    "dir", "smooth", "hand", "kit_state", "chain", "firstlast", "lines",
    "kf_status", "clip_status", "note",
]


def write_csv() -> None:
    path = ROOT / "shots" / "ep01-shotlist.csv"
    with path.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=CSV_FIELDS)
        w.writeheader()
        for s in SHOTS:
            w.writerow({
                "id": s["id"], "seq": s["seq"], "dur": s["dur"], "tool": s["tool"],
                "plate": s["plate"], "chars": " ".join(s["chars"]),
                "lens": s["lens"], "move": s["move"], "height": s["height"],
                "dir": s["dir"], "smooth": s["smooth"], "hand": s.get("hand") or "",
                "kit_state": s.get("kit_state") or "", "chain": s.get("chain") or "",
                "firstlast": "Y" if s.get("firstlast") else "",
                "lines": " ".join(s["lines"]),
                "kf_status": "todo", "clip_status": "todo",
                "note": s["note"],
            })
    print(f"  wrote tracker -> shots/ep01-shotlist.csv")


def write_cards() -> None:
    out = ROOT / "shots" / "sequences"
    out.mkdir(parents=True, exist_ok=True)
    for f in out.glob("*.md"):
        f.unlink()

    for seq, (title, _plate, light) in SEQUENCES.items():
        shots = [s for s in SHOTS if s["seq"] == seq]
        dur = sum(s["dur"] for s in shots)
        lines = [
            f"# SEQ {seq:02d} — {title}",
            "",
            f"**{len(shots)} shots · {dur}s ({dur // 60}:{dur % 60:02d}) · "
            f"{shots[0]['id']} – {shots[-1]['id']}**",
            "",
            f"**Lighting for this whole sequence:** {light}",
            "",
            "Full paste-ready prompts are in `prompts/SH-###.txt`. This file is the "
            "human-readable card set — read it before you generate, and read the note "
            "on every shot.",
            "",
        ]
        for s in shots:
            lines += [
                "---",
                "",
                f"## {s['id']} · {s['dur']}s · {s['tool']}",
                "",
                f"| | |",
                f"|---|---|",
                f"| **Plate** | `{s['plate']}` |",
                f"| **Characters** | {', '.join(s['chars']) or '—'} |",
                f"| **Camera** | {s['lens']}, {s['move']}, {s['height']} height |",
                f"| **Screen dir** | {s['dir']} |",
                f"| **Smooth horizon** | {s['smooth']} |",
                f"| **Hand** | {s.get('hand') or '—'} |",
                f"| **Chain from** | {s.get('chain') or '—'} |",
                f"| **First+last frame** | {'YES' if s.get('firstlast') else 'no'} |",
                f"| **Dialogue** | {', '.join(s['lines']) or '—'} |",
                f"| **Prompt file** | `prompts/{s['id']}.txt` |",
                "",
                f"**Action.** {s['action']}",
                "",
                f"> **Note.** {s['note']}",
                "",
            ]
        (out / f"seq-{seq:02d}.md").write_text("\n".join(lines))
    print(f"  wrote {len(SEQUENCES)} sequence cards -> shots/sequences/")


def main() -> int:
    print("FIRST LAYER — building production files")
    fails = validate()
    write_prompts()
    write_csv()
    write_cards()

    if fails:
        print("\nCONTINUITY FAILURES — fix before generating:")
        for f in fails:
            print(f"  FAIL  {f}")
        return 1
    print("\n  all continuity checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
